unbind C-b

set -g base-index 1
set -g default-terminal "xterm-256color"
set -g focus-events off
set -g prefix M-q
set -g status-left-length 128
set -g status-right "[%R | %d/%m/%G]"
set -g status-right-length 128

set -s escape-time 0

set-option -g allow-rename off
set-option -g status-position "top"

setw -g mode-keys vi
setw -g mouse on
setw -g history-limit 1024
setw -g pane-base-index 1

bind 'c' new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}" -v
bind '%' split-window -c "#{pane_current_path}" -h

bind -n M-l select-pane -L
bind -n M-h select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D
